 const products = [
  {
    title: "Magnetite",
    category: 1,
    price: 89.0,
    img: "assets/img/1.jpg",
    band: "Scalene",
    year: 2017,
    id: 0,
  },
  {
    title: "Acabou o Chorare",
    category: 2,
    price: 66.0,
    img: "assets/img/2.jpg",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nirvana Discografia",
    category: 3,
    price: 50.0,
    img: "assets/img/3.jpg",
    band: "Nirvava",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: 4,
    price: 22.0,
    img: "assets/img/4.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
  {
    title: "Testando o Som 5",
    category: 5,
    price: 100.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 5",
    year: 2022,
    id: 4,
  },
  {
    title: "Testando o Som 6",
    category: 6,
    price: 10.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 6",
    year: 2022,
    id: 5,
  },
  {
    title: "Testando o Som 7",
    category: 7,
    price: 55.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 7",
    year: 2022,
    id: 6,
  },
  {
    title: "Testando o Som 8",
    category: 8,
    price: 32.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 8",
    year: 2022,
    id: 7,
  },
  {
    title: "Testando o Som 9",
    category: 9,
    price: 72.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 9",
    year: 2022,
    id: 8,
  },
  {
    title: "Testando o Som 10",
    category: 10,
    price: 88.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 10",
    year: 2022,
    id: 9,
  },
  {
    title: "Testando o Som 11",
    category: 11,
    price: 18.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 11",
    year: 2022,
    id: 10,
  },
  {
    title: "Testando o Som 12",
    category: 1,
    price: 99.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 12",
    year: 2017,
    id: 11,
  },
  {
    title: "Testando o Som 13",
    category: 2,
    price: 35.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 13",
    year: 1972,
    id: 12,
  },
  {
    title: "Testando o Som 14",
    category: 3,
    price: 21.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 14",
    year: 1990,
    id: 13,
  },
  {
    title: "Testando o Som 15",
    category: 4,
    price: 350.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 15",
    year: 1993,
    id: 14,
  },
  {
    title: "Testando o Som 16",
    category: 5,
    price: 250.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 16",
    year: 2022,
    id: 15,
  },
  {
    title: "Testando o Som 17",
    category: 6,
    price: 37.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 17",
    year: 2022,
    id: 16,
  },
  {
    title: "Testando o Som 18",
    category: 7,
    price: 5.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 18",
    year: 2022,
    id: 17,
  },
  {
    title: "Testando o Som 19",
    category: 8,
    price: 69.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 19",
    year: 2022,
    id: 18,
  },
  {
    title: "Testando o Som 20",
    category: 9,
    price: 53.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 20",
    year: 2022,
    id: 19,
  },
  {
    title: "Testando o Som 21",
    category: 10,
    price: 18.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 21",
    year: 2022,
    id: 20,
  },
  {
    title: "Testando o Som 22",
    category: 11,
    price: 150.0,
    img: "assets/img/5.jpg",
    band: "Aleatório 22",
    year: 2022,
    id: 21,
  },
];

const categories = [
  "Todos",
  "Pop",
  "MPB",
  "Forró",
  "Samba",
  "Baião",
  "Rap",
  "Hip-Hop",
  "Rock",
  "Reggae",
  "Country",
  "Gospel",
];